### ISSUE TITLE
Patched.

### ISSUE THREAD

**Issue by x8g** [jgord559/Tiktok-AutoClaimer#4]
Please update the api or something, the checker part of it works 100% it just doesnt claim like its supposed to and add webhook features. Like when it claims it sends a message to the webhook or when its available you know. Please contact me zt#1337

**Comment by votlng** [comment]
The claiming endpoint is patched tiktok changes there endpoint to prevent this happening you will have to ask so e to teach you how to get the endpoints or pay someone

**Comment by jgord559** [comment]
the error that is in the response is "{"data":{"captcha":"","desc_url":"Please see https://zjsms.com/JeBd2LH/ for help","description":"This application has no permissions","error_code":16},"message":"error"}" This is because the request is not being sent with values that are now needed. The url request in the code at the moment does not have the values now needed.  "https://www.tiktok.com/api/update/profile/?aid=1988&app_language=en&app_name=tiktok_web&battery_info=1&browser_language=en-GB&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F102.0.5005.63%20Safari%2F537.36&channel=tiktok_web&cookie_enabled=true&device_id=7104752947023857157&device_platform=web_pc&focus_state=true&from_page=user&history_len=3&is_fullscreen=false&is_page_visible=true&os=windows&priority_region=GB&referer=https%3A%2F%2Fwww.tiktok.com%2F&region=GB&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&screen_height=1080&screen_width=1920&tz_name=Europe%2FLondon&verifyFp=verify_l3xihqw9_u6pTlpf8_Lyel_4gmV_9dth_qFesH3gVQVyT&webcast_language=en&msToken=y8zq1fGNlW7y-Vg8TvcYlE-hGLky5v0yWnbKm4-aUlRzL7K-czcd1ugwV3OR3TIctpYkBvyltEjZPQsOrosFewn6xn2-h-Pbfv_FcNvLEItXDCNWKRGxRYQRcfuboyk=&X-Bogus=DFSzswVLZNDsWJd-SwHNdsXyYJUF&_signature=_02B4Z6wo00001abd.WAAAIDAhXzTzqT9B1Wm3fnAAAsv3b" is working if you replace all the values with your own it will work. Sorry but i do not have time to put this in the code rn
